/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author marti
 */
public class FileChooserWindow extends javax.swing.JFrame {

    /**
     * Creates new form FileChooserWindow
     */
    public FileChooserWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PathDisplay = new javax.swing.JTextField();
        InfoFileChooserWindow = new javax.swing.JLabel();
        FileChooserButton = new javax.swing.JButton();
        NextWindow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PathDisplay.setEditable(false);
        PathDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(PathDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 330, -1));

        InfoFileChooserWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoFileChooserWindow.setText("Debes elegir un archivo para cargar el programa. En caso de no elegir un archivo se cargara uno por defecto.");
        jPanel1.add(InfoFileChooserWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 310, 80));

        FileChooserButton.setText("...");
        FileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserButtonActionPerformed(evt);
            }
        });
        jPanel1.add(FileChooserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 40, -1));

        NextWindow.setText("Ir al menu");
        NextWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextWindowActionPerformed(evt);
            }
        });
        jPanel1.add(NextWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PathDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathDisplayActionPerformed

    private void FileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int selection = fc.showOpenDialog(this);
        
        if (selection == JFileChooser.APPROVE_OPTION) {
            File path = fc.getSelectedFile();
            PathDisplay.setText(path.getAbsolutePath());
        }
    }//GEN-LAST:event_FileChooserButtonActionPerformed

    private void NextWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextWindowActionPerformed
        // Abrir el menu
    }//GEN-LAST:event_NextWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooserWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FileChooserButton;
    private javax.swing.JLabel InfoFileChooserWindow;
    private javax.swing.JButton NextWindow;
    private javax.swing.JTextField PathDisplay;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
